image: node:6.9.5
pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - typedoc src/index.ts --excludePrivate --mode file --theme minimal --out build/docs
  artifacts:
    paths:
    - build/docs/
  only:
    - master