image: node:6.9.5
pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - ./node_modules/.bin/typedoc src/index.ts --excludePrivate --mode file --theme minimal --out docs
  artifacts:
    paths:
    - docs/
  only:
    - master